# Generated by Django 4.2.1 on 2023-05-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_store',
            field=models.BooleanField(default=False),
        ),
    ]
