# Generated by Django 4.2.1 on 2023-05-27 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_has_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='has_store',
        ),
    ]
