# Generated by Django 4.2.1 on 2023-05-25 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_has_store'),
        ('products', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchaser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
